service: notes-api

# Create an optimized package for our functions
package:
  individually: true # Ensures that functions are packaged individually instead of together

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: ap-southeast-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get